### ISSUE TITLE
Video freezing, but stream is still receiving data

### ISSUE THREAD

**Issue by gregoryjjb** [feross/mediasource#10]
Hi there! Great tool, it's exactly what I needed. As the title says, however, my videos freeze after 10 or so seconds (it's not the same every time) but the stream is still getting data just fine.

Here's my code snippet. I'm using socket.io to handle the stream from server-to-browser. I logged out the data the stream was receiving and it keeps going just fine after the freeze. There's no error message. Do you have any ideas about how I could debug this? Possible causes?

```
ss(this.socket).on('vid-back', backStream => {
                        
    console.log("Server opened backwards stream");
    
    var elem = document.querySelector('#stream-video');
    var wrapper = new MediaElementWrapper(elem);
    var writable = wrapper.createWriteStream('video/webm; codecs="vp8"');
    
    elem.addEventListener('error', function () {
        var errorCode = elem.error
        var detailedError = wrapper.detailedError
        console.error(errorCode);
        console.error(detailedError);
    })
    
    backStream.pipe(writable);
    
    backStream.on('data', data => {
        console.log('> Received blob of data');
    })
})
```

**Comment by feross** [comment]
This package uses the MediaSource API in an extremely naive way. For an approach that is more likely to work for all video files, and supports seeking, take a look at [videostream](https://github.com/jhiesey/videostream).

Or for a package that tries multiple approaches, including `videostream` and this package (`mediasource`), as well as a Blob API (non-streaming) approach, and works for many non-video file types, consider [render-media](https://github.com/feross/render-media).

**Comment by gregoryjjb** [comment]
Thanks, I'll check those out.

**Comment by gregoryjjb** [comment]
For future readers: My problem was my streaming webm video (coming from ffmpeg) wasn't keyframed properly. By adding `-g 1` to my ffmpeg call I set every frame to be a keyframe and eliminated the freezing issue entirely. See also [this stackoverflow thread](https://stackoverflow.com/a/24223762).

**Comment by feross** [comment]
Thanks for sharing @gregdumb

**Comment by bberberoglu** [comment]
> coming

please share your ffmpeg command ?

**Comment by bberberoglu** [comment]
> For future readers: My problem was my streaming webm video (coming from ffmpeg) wasn't keyframed properly. By adding `-g 1` to my ffmpeg call I set every frame to be a keyframe and eliminated the freezing issue entirely. See also [this stackoverflow thread](https://stackoverflow.com/a/24223762).

please share your ffmpeg command ?

**Comment by gregoryjjb** [comment]
https://github.com/gregoryjjb/cs160-server/blob/64a5f0134e818536d4511421bbc5c981618ac3a1/utils/processing.js#L65-L69

It's been a while since I did this and it looks like I didn't format my args correctly (I have a bunch on that last line) but you can see that `-g 1` on the end there. I was able to get relatively smooth streaming with that command, although from my understanding `-g 1` will decrease performance because keyframes take up more bandwidth.
