### ISSUE TITLE
DOMException: "The quota has been exceeded."

### ISSUE THREAD

**Issue by PaulBGD** [feross/mediasource#21]
This has been happening in Firefox with high definition files which have a higher bitrate. When we move around the video quick, the buffer fills up very fast and doesn't seem to empty fast enough for Firefox. 

I found this issue that might help when I was looking around at other projects. https://github.com/videojs/http-streaming/issues/192

**Comment by PaulBGD** [comment]
I took a stab at fixing this, but it appears it's a lot harder than just calling `sourceBuffer.remove()`, as it's hard to figure out what doesn't need to exist.

**Comment by feross** [comment]
Since there's already an issue on `videostream`, I'm going to close this issue in favor of: https://github.com/jhiesey/videostream/issues/35
