### ISSUE TITLE
Inheritance not working as expected?

### ISSUE THREAD

**Issue by makinje16** [feross/mediasource#27]
Currently I am trying to use `mediasource` along with `media-recorder-stream` to send audio and video over an rtc datachannel. I looked at the usage section in the README but am running into an issue. We are using react as a frontend framework but I don't believe that could be the root cause of this.

```
// Create writeable stream for the remote video elem
  var wrapper = new MediaElementWrapper(playbackVideoRemote);
  var writeable = wrapper.createWriteStream("audio/webm; codecs=pcm")
  if(peerReadableStream.locked) {
    console.log("read stream is locked");
  } else {
    console.log("Not locked")
  }
  if(writeable.locked) {
    console.log("Write is locked");
  } else {
    console.log("Not locked");
  }
  try {
    console.log(writeable);
    peerReadableStream.pipeTo(writeable);
  }
  catch(err) {
    console.log(err);
  }
```

The code above is where I'm running into an error. I am getting an illegal invocation on pipeTo because `writeable` in this instance is a MediaSourceStream and not a WriteableStream. I looked at the source code and see that MediaSourceStream inherits Writeablestream but is there a reason that the inheritance is not working in this instance? The console.log statements were when I first thought the streams may be locked already but they turned out not to be.

**Comment by feross** [comment]
The writeable stream that is returned is a Node.js stream, not a WHATWG stream.

**Comment by makinje16** [comment]
Ah thank you so much! That small answer really just unblocked me 🙏
