### ISSUE TITLE
h264 with Chrome

### ISSUE THREAD

**Issue by supernoveau** [feross/mediasource#8]
I have the mp4 / h264 codec working with Firefox v49.0.2, using: `video/mp4; codecs="avc1.64001e, mp4a.40.2"`.

However, this doesn't stream for Chrome v55.0.2883.87.

According to `window.MediaSource.isTypeSupported('video/mp4; codecs="avc1.64001e, mp4a.40.2"')`, the type is supported in the Chrome browser.

Also, test file is fragmented and video is definitely using this version of the codec (tested using http://nickdesaulniers.github.io/mp4info/ and mp4file.

Any ideas what may be the problem?

**Comment by feross** [comment]
Mediasource is very picky about the files that it accepts. There's probably some issue with the file you're providing that makes Chrome not happy with. I suggest taking a really close look at all the mp4 details using a tool like mp4box or even mp4-parser.

**Comment by supernoveau** [comment]
Thanks @feross !

**Comment by supernoveau** [comment]
FYI the problem was that the fragmentation wasn't applied to the keyframes under `-movflags default_base_moof+frag_keyframe`.

Full encode command to have this accepted by Chrome (using baseline and level 3):

`ffmpeg -i ~/path/to/original.MOV -c:v libx264 -profile:v baseline -level 3.0 -c:a libfdk_aac -b:a 128k -f mp4 -reset_timestamps 1 -movflags empty_moov+default_base_moof+frag_keyframe+faststart ~/path/to/output.mp4`

**Comment by feross** [comment]
Glad you got it figured out! What a command! `ffmpeg` is true dark magic.
